[project]
name = "adgenius-ai-hackathon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.11.10",
    "pydantic-ai[examples,logfire]>=0.0.12",
    "python-dotenv>=1.0.1",
]
